### ISSUE TITLE
Can the version pinning of `pytest` be relaxed?

### ISSUE THREAD

**Issue by nvaytet** [SasView/sasdata#32]
`pytest` is currently pinned to `<6` in the [setup.py](https://github.com/SasView/sasdata/blob/master/setup.py#L85).

Can I ask what is the reason for this, and can this be relaxed? This is not playing well inside a `conda` environment with `conda` and `pip` packages, as `conda` wants to rely on version `7.2`, which no longer needs the package `py` to be installed (see note [here](https://pylib.readthedocs.io/en/stable/)).

**Comment by krzywon** [comment]
Thanks for catching this. The requirements here were taken from the sasview\sasview requirements to minimize conflicts. The sasview requirements have been relaxed, so we should also do the same here.
