### ISSUE TITLE
Failing Unit Tests: MacOS and Ubuntu

### ISSUE THREAD

**Issue by krzywon** [SasView/sasdata#57]
Two unit tests are failing for both MacOS and Ubuntu, across all versions of Python. These tests are successful under Windows.

Link to failing job: https://github.com/SasView/sasdata/actions/runs/7573626662/job/20626178693

Error Message:

> test/sasdataloader/utest_extension_registry.py:95: AssertionError
=========================== short test summary info ============================
FAILED test/sasdataloader/utest_cansas.py::cansas_reader_xml::test_invalid_cansas - AssertionError: False is not true
FAILED test/sasdataloader/utest_extension_registry.py::ExtensionRegistryTests::test_data_reader_exception - AssertionError: 4 != 1
========================= 2 failed, 98 passed in 6.50s =========================

**Comment by krzywon** [comment]
A quick investigation suggests changes made in the lxml library are the cause of the unit test failures. More investigation is required. In the mean time, a PR has been submitted to limit lxml to versions less than 5.

**Comment by llimeht** [comment]
As an additional data point, the test suite from sasdata version 0.8.1 passed on Debian's CI with python3-lxml version 5.1.0-1. Have these tests or those code paths changed since then? 
https://ci.debian.net/packages/s/sasdata/testing/amd64/41845113/

**Comment by krzywon** [comment]
This issue has been resolved, but only for the short-term. #64 is more specific to the long-term issue so I am closing this.
